require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/tmp/**/*'
    - 'config/puma.rb'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
    - 'config/initializers/secret_token.rb'
    - 'lib/tasks/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false


