name: Code style

on: [pull_request]

jobs:
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      - run: bundle install
      - name: rubocop
        run: bundle exec rubocop --parallel
